package com.example.template

import com.example.model.TemplateCategory

object TemplateRepository {

  val templates: List<TemplateDefinition> = listOf(
    // ==========================================
    // 1. ATS / CORPORATE (10 Distinct Templates)
    // ==========================================
    TemplateDefinition(
      id = "ats_classic",
      name = "ATS Classic",
      category = TemplateCategory.ATS,
      atsScore = 99,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#1F1F1F",
      secondaryColorHex = "#5E5752",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Strictly sequential standard ATS layout. Linear parsing order, zero complex columns.",
      tags = listOf("ATS 99%", "Single Column", "High Parsing")
    ),
    TemplateDefinition(
      id = "ats_modern",
      name = "ATS Modern",
      category = TemplateCategory.ATS,
      atsScore = 96,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#72232B",
      secondaryColorHex = "#333333",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "Linear ATS-safe architecture with Careeré Burgundy section dividers and crisp hierarchy.",
      tags = listOf("ATS 96%", "Careeré Theme", "Recommended")
    ),
    TemplateDefinition(
      id = "corporate_clean",
      name = "Corporate Clean",
      category = TemplateCategory.ATS,
      atsScore = 94,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#212B38",
      secondaryColorHex = "#4A5568",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Executive corporate hierarchy with refined serif title typography and structured dates.",
      tags = listOf("Corporate", "Finance", "Consulting")
    ),
    TemplateDefinition(
      id = "executive_pro",
      name = "Executive Pro",
      category = TemplateCategory.ATS,
      atsScore = 92,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.HEADER_ACCENT,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#1A365D",
      secondaryColorHex = "#2C5282",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "Distinguished executive format with prominent header panel and achievement metrics.",
      tags = listOf("Leadership", "Director", "Photo Ready")
    ),
    TemplateDefinition(
      id = "consulting_standard",
      name = "Consulting Standard",
      category = TemplateCategory.ATS,
      atsScore = 95,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#1F2937",
      secondaryColorHex = "#4B5563",
      dividerStyle = DividerStyle.NONE,
      description = "McKinsey/Bain inspired case-oriented structure emphasizing quantified impact bullets.",
      tags = listOf("Consulting", "Strategy", "Impact")
    ),
    TemplateDefinition(
      id = "banking_finance",
      name = "Banking & Capital",
      category = TemplateCategory.ATS,
      atsScore = 95,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#1B2A4A",
      secondaryColorHex = "#334155",
      dividerStyle = DividerStyle.DOUBLE_LINE,
      description = "Wall Street & London City investment banking convention with double-ruled dividers.",
      tags = listOf("Banking", "M&A", "Investment")
    ),
    TemplateDefinition(
      id = "business_minimal",
      name = "Business Minimal",
      category = TemplateCategory.ATS,
      atsScore = 97,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.HUMANIST_CLEAN,
      primaryAccentHex = "#27272A",
      secondaryColorHex = "#52525B",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Clean, breathable ATS-ready layout with warm humanist typography.",
      tags = listOf("General", "Versatile", "Fast")
    ),
    TemplateDefinition(
      id = "management_prime",
      name = "Management Prime",
      category = TemplateCategory.ATS,
      atsScore = 93,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.TWO_COLUMN_LEFT,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#18181B",
      secondaryColorHex = "#71717A",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "Two-column ATS-tested architecture with left competencies rail.",
      tags = listOf("Management", "Operations", "Two Column")
    ),
    TemplateDefinition(
      id = "enterprise_lead",
      name = "Enterprise Lead",
      category = TemplateCategory.ATS,
      atsScore = 94,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#111827",
      secondaryColorHex = "#374151",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "Engineered for technical enterprise directors and VP level profiles.",
      tags = listOf("Tech VP", "Architect", "High Impact")
    ),
    TemplateDefinition(
      id = "legal_advocate",
      name = "Legal & Compliance",
      category = TemplateCategory.ATS,
      atsScore = 98,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#1C1917",
      secondaryColorHex = "#44403C",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Formal, authoritative legal resume format adhering to strict judicial & law firm norms.",
      tags = listOf("Legal", "Judicial", "Editorial")
    ),

    // ==========================================
    // 2. MINIMAL & SWISS (10 Distinct Templates)
    // ==========================================
    TemplateDefinition(
      id = "swiss_precision",
      name = "Swiss Precision",
      category = TemplateCategory.MINIMAL,
      atsScore = 91,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.BORDERED_MINIMAL,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#1F1F1F",
      secondaryColorHex = "#72232B",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Inspired by Josef Müller-Brockmann grid design. Strict geometric baseline and subtle Burgundy accent.",
      tags = listOf("Swiss Grid", "Ultra Clean", "Designers")
    ),
    TemplateDefinition(
      id = "minimal_pure",
      name = "Pure Minimal",
      category = TemplateCategory.MINIMAL,
      atsScore = 95,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#18181B",
      secondaryColorHex = "#71717A",
      dividerStyle = DividerStyle.NONE,
      description = "Zero borders, zero distractions. Relies purely on typographic scale and negative space.",
      tags = listOf("Typographic", "Minimalist", "Modern")
    ),
    TemplateDefinition(
      id = "careere_editorial",
      name = "Careeré Editorial",
      category = TemplateCategory.MINIMAL,
      atsScore = 93,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.SPLIT_PANEL,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#72232B",
      secondaryColorHex = "#C9A3A6",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "The definitive Careeré brand template. Refined French serif titles with warm stone borders.",
      tags = listOf("Flagship", "Editorial Serif", "Warm Ivory")
    ),
    TemplateDefinition(
      id = "nordic_monochrome",
      name = "Nordic Mono",
      category = TemplateCategory.MINIMAL,
      atsScore = 94,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#0F172A",
      secondaryColorHex = "#64748B",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Scandinavian calm minimalism with airy margins and muted slate hierarchy.",
      tags = listOf("Nordic", "Balanced", "Light")
    ),
    TemplateDefinition(
      id = "bauhaus_grid",
      name = "Bauhaus Grid",
      category = TemplateCategory.MINIMAL,
      atsScore = 90,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.BORDERED_MINIMAL,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#1C1917",
      secondaryColorHex = "#78716C",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "Asymmetric modernist layout celebrating function, geometric proportion, and clarity.",
      tags = listOf("Bauhaus", "Architectural", "Clean")
    ),
    TemplateDefinition(
      id = "monospace_tech",
      name = "Monospace Code",
      category = TemplateCategory.MINIMAL,
      atsScore = 92,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.MONO_TECHNICAL,
      primaryAccentHex = "#0D1117",
      secondaryColorHex = "#58A6FF",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Engineered for kernel, backend, and protocol developers with monospaced metadata.",
      tags = listOf("Dev", "Monospace", "Terminal")
    ),
    TemplateDefinition(
      id = "zurich_compact",
      name = "Zurich Compact",
      category = TemplateCategory.MINIMAL,
      atsScore = 92,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.TWO_COLUMN_RIGHT,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#262626",
      secondaryColorHex = "#525252",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Dense, space-optimized 1-page CV layout ideal for extensive skill catalogs.",
      tags = listOf("1-Page", "Dense", "Efficient")
    ),
    TemplateDefinition(
      id = "parisienne_serif",
      name = "Parisienne",
      category = TemplateCategory.MINIMAL,
      atsScore = 91,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#5C1B22",
      secondaryColorHex = "#8B2E38",
      dividerStyle = DividerStyle.ACCENT_DOT,
      description = "High-contrast editorial serif layout echoing classic French publishing houses.",
      tags = listOf("Paris", "Publishing", "Literary")
    ),
    TemplateDefinition(
      id = "lucerne_pure",
      name = "Lucerne",
      category = TemplateCategory.MINIMAL,
      atsScore = 93,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.HUMANIST_CLEAN,
      primaryAccentHex = "#1E293B",
      secondaryColorHex = "#475569",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Gentle, approachable simplicity for administrative and advisory careers.",
      tags = listOf("Approach", "Warm", "Clean")
    ),
    TemplateDefinition(
      id = "atelier_minimal",
      name = "Atelier",
      category = TemplateCategory.MINIMAL,
      atsScore = 90,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.SPLIT_PANEL,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#27272A",
      secondaryColorHex = "#A1A1AA",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Craft studio layout with subtle hairline framing and distinct project highlights.",
      tags = listOf("Studio", "Craft", "Split")
    ),

    // ==========================================
    // 3. CREATIVE & DESIGN (10 Distinct Templates)
    // ==========================================
    TemplateDefinition(
      id = "creative_studio",
      name = "Creative Studio",
      category = TemplateCategory.CREATIVE,
      atsScore = 86,
      isAtsSafe = false,
      supportsPhoto = true,
      layout = LayoutStructure.SPLIT_PANEL,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#72232B",
      secondaryColorHex = "#C9A3A6",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "Dual-tone creative split layout with burgundy side block and editorial typography.",
      tags = listOf("Design", "Creative", "Split Panel")
    ),
    TemplateDefinition(
      id = "contemporary_bold",
      name = "Contemporary Bold",
      category = TemplateCategory.CREATIVE,
      atsScore = 88,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.HEADER_ACCENT,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#18181B",
      secondaryColorHex = "#72232B",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "High-contrast visual header with bold uppercase headings and clean project cards.",
      tags = listOf("Art Director", "Bold", "Modern")
    ),
    TemplateDefinition(
      id = "portfolio_visual",
      name = "Visual Portfolio",
      category = TemplateCategory.CREATIVE,
      atsScore = 85,
      isAtsSafe = false,
      supportsPhoto = true,
      layout = LayoutStructure.MODERN_CARD,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#312E81",
      secondaryColorHex = "#6366F1",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Framed cards highlighting key case studies, URLs, and multi-disciplinary toolkits.",
      tags = listOf("UX/UI", "Product Design", "Cards")
    ),
    TemplateDefinition(
      id = "vibrant_edge",
      name = "Vibrant Edge",
      category = TemplateCategory.CREATIVE,
      atsScore = 87,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.TWO_COLUMN_LEFT,
      typography = TypographyStyle.HUMANIST_CLEAN,
      primaryAccentHex = "#065F46",
      secondaryColorHex = "#10B981",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Deep emerald accent with left profile pane and rich achievement tags.",
      tags = listOf("Emerald", "Media", "PR")
    ),
    TemplateDefinition(
      id = "gallery_split",
      name = "Gallery Split",
      category = TemplateCategory.CREATIVE,
      atsScore = 84,
      isAtsSafe = false,
      supportsPhoto = true,
      layout = LayoutStructure.SPLIT_PANEL,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#4A0E17",
      secondaryColorHex = "#D8D1C7",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Exhibition catalogue layout tailored for photographers, curators, and architects.",
      tags = listOf("Curator", "Exhibition", "Fine Art")
    ),
    TemplateDefinition(
      id = "editorial_magazine",
      name = "Editorial Magazine",
      category = TemplateCategory.CREATIVE,
      atsScore = 89,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.TWO_COLUMN_RIGHT,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#1C1917",
      secondaryColorHex = "#72232B",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "New Yorker & Monocle inspired layout with right pull-quotes and publications column.",
      tags = listOf("Journalism", "Copywriting", "Editorial")
    ),
    TemplateDefinition(
      id = "product_craft",
      name = "Product Craft",
      category = TemplateCategory.CREATIVE,
      atsScore = 90,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.HEADER_ACCENT,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#0F766E",
      secondaryColorHex = "#14B8A6",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "Clean modern tech product manager layout balancing roadmap achievements and metrics.",
      tags = listOf("Product", "Tech", "SaaS")
    ),
    TemplateDefinition(
      id = "architect_folio",
      name = "Architect Folio",
      category = TemplateCategory.CREATIVE,
      atsScore = 88,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.BORDERED_MINIMAL,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#262626",
      secondaryColorHex = "#737373",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Hairline structural divisions, drawing-sheet coordinates, and project specifications.",
      tags = listOf("Architect", "Structural", "Folio")
    ),
    TemplateDefinition(
      id = "brand_stylist",
      name = "Brand Stylist",
      category = TemplateCategory.CREATIVE,
      atsScore = 86,
      isAtsSafe = false,
      supportsPhoto = true,
      layout = LayoutStructure.TWO_COLUMN_LEFT,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#831843",
      secondaryColorHex = "#F472B6",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Luxury fashion and lifestyle brand format with circular avatar and delicate typography.",
      tags = listOf("Fashion", "Stylist", "Luxury")
    ),
    TemplateDefinition(
      id = "indie_founder",
      name = "Indie Founder",
      category = TemplateCategory.CREATIVE,
      atsScore = 91,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#1E1B4B",
      secondaryColorHex = "#4338CA",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "Showcases bootstrapped revenue metrics, product traction, and full-stack ownership.",
      tags = listOf("Founder", "Startup", "Generalist")
    ),

    // ==========================================
    // 4. STUDENT / FRESHER (10 Distinct Templates)
    // ==========================================
    TemplateDefinition(
      id = "student_ats",
      name = "Student ATS Clean",
      category = TemplateCategory.STUDENT,
      atsScore = 98,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#1F1F1F",
      secondaryColorHex = "#4B5563",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Puts Education, Relevant Coursework, and Capstone Projects at top for campus hiring.",
      tags = listOf("ATS Safe", "Education First", "Freshers")
    ),
    TemplateDefinition(
      id = "graduate_modern",
      name = "Graduate Modern",
      category = TemplateCategory.STUDENT,
      atsScore = 94,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#72232B",
      secondaryColorHex = "#4A5568",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "Modern university graduate layout with Careeré Burgundy accents and structured skills.",
      tags = listOf("Graduates", "Internships", "Honors")
    ),
    TemplateDefinition(
      id = "internship_launch",
      name = "Internship Launch",
      category = TemplateCategory.STUDENT,
      atsScore = 96,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.HUMANIST_CLEAN,
      primaryAccentHex = "#0369A1",
      secondaryColorHex = "#0284C7",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Dedicated section layout for summer internships, student societies, and leadership.",
      tags = listOf("Intern", "Societies", "Projects")
    ),
    TemplateDefinition(
      id = "campus_fellow",
      name = "Campus Fellow",
      category = TemplateCategory.STUDENT,
      atsScore = 93,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.TWO_COLUMN_LEFT,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#1E293B",
      secondaryColorHex = "#64748B",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Compact two-column fresher format with left education sidebar and right projects body.",
      tags = listOf("Compact", "Campus", "Two-Col")
    ),
    TemplateDefinition(
      id = "first_job_pro",
      name = "First Job Pro",
      category = TemplateCategory.STUDENT,
      atsScore = 95,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#111827",
      secondaryColorHex = "#374151",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "Balanced spacing engineered to fill a complete single page without awkward gaps.",
      tags = listOf("1-Page Fill", "No Experience", "Entry")
    ),
    TemplateDefinition(
      id = "academic_scholar",
      name = "Academic Scholar",
      category = TemplateCategory.STUDENT,
      atsScore = 95,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#3F2C1D",
      secondaryColorHex = "#785C42",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Formal university template for Master's/Ph.D. candidates with research citations.",
      tags = listOf("Scholar", "Thesis", "Research")
    ),
    TemplateDefinition(
      id = "tech_graduate",
      name = "Tech Graduate",
      category = TemplateCategory.STUDENT,
      atsScore = 96,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.MONO_TECHNICAL,
      primaryAccentHex = "#0F172A",
      secondaryColorHex = "#38BDF8",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Highlights hackathon awards, GitHub repos, and computer science coursework.",
      tags = listOf("CS Major", "Hackathons", "GitHub")
    ),
    TemplateDefinition(
      id = "business_school_msc",
      name = "Business School MSc",
      category = TemplateCategory.STUDENT,
      atsScore = 94,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.HEADER_ACCENT,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#1E3A8A",
      secondaryColorHex = "#3B82F6",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "HEC/ESSEC/LBS standard format for pre-experience Master in Management candidates.",
      tags = listOf("MiM", "Business School", "Finance")
    ),
    TemplateDefinition(
      id = "medical_resident",
      name = "Medical Resident",
      category = TemplateCategory.STUDENT,
      atsScore = 96,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#0E7490",
      secondaryColorHex = "#155E75",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Clinical rotations, hospital internships, medical certifications, and licensures.",
      tags = listOf("Healthcare", "Resident", "Clinical")
    ),
    TemplateDefinition(
      id = "student_minimalist",
      name = "Student Minimalist",
      category = TemplateCategory.STUDENT,
      atsScore = 95,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.HUMANIST_CLEAN,
      primaryAccentHex = "#262626",
      secondaryColorHex = "#737373",
      dividerStyle = DividerStyle.NONE,
      description = "Elegant and honest entry-level resume focusing on competencies and adaptability.",
      tags = listOf("Simple", "Versatile", "Fast")
    ),

    // ==========================================
    // 5. EXECUTIVE & LEADERSHIP (8 Distinct Templates)
    // ==========================================
    TemplateDefinition(
      id = "executive_director",
      name = "Executive Director",
      category = TemplateCategory.EXECUTIVE,
      atsScore = 93,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.HEADER_ACCENT,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#72232B",
      secondaryColorHex = "#1F1F1F",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Flagship executive layout. Prominent career summary, board experience, and P&L achievements.",
      tags = listOf("C-Suite", "Board Ready", "P&L")
    ),
    TemplateDefinition(
      id = "csuite_prime",
      name = "C-Suite Prime",
      category = TemplateCategory.EXECUTIVE,
      atsScore = 92,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.TWO_COLUMN_LEFT,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#0F172A",
      secondaryColorHex = "#334155",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "Architected for CEO/COO/CFO profiles with left board advisory panel.",
      tags = listOf("CEO/CFO", "Advisory", "Two-Col")
    ),
    TemplateDefinition(
      id = "boardroom_leader",
      name = "Boardroom Leader",
      category = TemplateCategory.EXECUTIVE,
      atsScore = 95,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#1F2937",
      secondaryColorHex = "#4B5563",
      dividerStyle = DividerStyle.DOUBLE_LINE,
      description = "Authoritative single-column board resume with distinguished serif headers.",
      tags = listOf("Governance", "Audit Committee", "Board")
    ),
    TemplateDefinition(
      id = "strategic_partner",
      name = "Strategic Partner",
      category = TemplateCategory.EXECUTIVE,
      atsScore = 94,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#1E293B",
      secondaryColorHex = "#64748B",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Senior management consulting partner format focusing on client engagements and billings.",
      tags = listOf("Partner", "Consulting", "Revenue")
    ),
    TemplateDefinition(
      id = "vp_enterprise",
      name = "VP Enterprise",
      category = TemplateCategory.EXECUTIVE,
      atsScore = 92,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.SPLIT_PANEL,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#18181B",
      secondaryColorHex = "#52525B",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "Split-panel layout tailored for VP Sales, VP Product, and enterprise growth leaders.",
      tags = listOf("VP Sales", "Growth", "Quota")
    ),
    TemplateDefinition(
      id = "managing_director",
      name = "Managing Director",
      category = TemplateCategory.EXECUTIVE,
      atsScore = 94,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#2E1065",
      secondaryColorHex = "#5B21B6",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Refined deep imperial violet accents for private equity and investment directors.",
      tags = listOf("Private Equity", "MD", "Capital")
    ),
    TemplateDefinition(
      id = "operations_chief",
      name = "Operations Chief",
      category = TemplateCategory.EXECUTIVE,
      atsScore = 93,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.TWO_COLUMN_RIGHT,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#1E3A8A",
      secondaryColorHex = "#2563EB",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Supply chain, manufacturing, and transformation executive format with right metrics rail.",
      tags = listOf("COO", "Supply Chain", "Metrics")
    ),
    TemplateDefinition(
      id = "governance_chair",
      name = "Governance & Non-Exec",
      category = TemplateCategory.EXECUTIVE,
      atsScore = 96,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#1C1917",
      secondaryColorHex = "#78716C",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Reserved exclusively for NEDs (Non-Executive Directors) and committee chairs.",
      tags = listOf("NED", "Non-Executive", "Governance")
    ),

    // ==========================================
    // 6. INTERNATIONAL & GLOBAL (8 Distinct Templates)
    // ==========================================
    TemplateDefinition(
      id = "europass_clean",
      name = "Europass Modernized",
      category = TemplateCategory.GLOBAL,
      atsScore = 93,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.TWO_COLUMN_LEFT,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#003399", // EU Blue
      secondaryColorHex = "#4A5568",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "ORIGINAL modern reimagining of European standard layout with CEFR language ratings.",
      tags = listOf("Europe", "CEFR Languages", "EU Standard")
    ),
    TemplateDefinition(
      id = "global_professional",
      name = "Global Professional",
      category = TemplateCategory.GLOBAL,
      atsScore = 95,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#72232B",
      secondaryColorHex = "#1F1F1F",
      dividerStyle = DividerStyle.SOLID_BAR,
      description = "International standard supporting multi-currency figures and country dialing formats.",
      tags = listOf("Expat", "International", "Careeré")
    ),
    TemplateDefinition(
      id = "diplomatic_envoy",
      name = "Diplomatic Envoy",
      category = TemplateCategory.GLOBAL,
      atsScore = 94,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.HEADER_ACCENT,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#1E293B",
      secondaryColorHex = "#475569",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "NGO, United Nations, and foreign service format with diplomatic mission details.",
      tags = listOf("UN", "NGO", "Diplomatic")
    ),
    TemplateDefinition(
      id = "transatlantic_standard",
      name = "Transatlantic",
      category = TemplateCategory.GLOBAL,
      atsScore = 96,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#1F2937",
      secondaryColorHex = "#4B5563",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Seamlessly dual-configured for US Letter and European A4 page dimensions.",
      tags = listOf("US & EU", "Dual Format", "Bilingual")
    ),
    TemplateDefinition(
      id = "singapore_hub",
      name = "Singapore Global",
      category = TemplateCategory.GLOBAL,
      atsScore = 94,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.TWO_COLUMN_RIGHT,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#831843",
      secondaryColorHex = "#9D174D",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "APAC regional headquarters format highlighting cross-border jurisdiction leadership.",
      tags = listOf("APAC", "Singapore", "Regional")
    ),
    TemplateDefinition(
      id = "nordic_global",
      name = "Nordic Global",
      category = TemplateCategory.GLOBAL,
      atsScore = 95,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.HUMANIST_CLEAN,
      primaryAccentHex = "#0F766E",
      secondaryColorHex = "#115E59",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Clean Scandinavian multilateral resume format popular in Stockholm, Oslo, and Copenhagen.",
      tags = listOf("Nordic", "Multilateral", "Clean")
    ),
    TemplateDefinition(
      id = "tokyo_bilingual",
      name = "Tokyo Global Tech",
      category = TemplateCategory.GLOBAL,
      atsScore = 93,
      isAtsSafe = true,
      supportsPhoto = true,
      layout = LayoutStructure.MODERN_CARD,
      typography = TypographyStyle.SANS_SWISS,
      primaryAccentHex = "#18181B",
      secondaryColorHex = "#71717A",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Compact structured cards meeting international tech hiring standards across Asia-Pacific.",
      tags = listOf("Tokyo", "Global Tech", "Structured")
    ),
    TemplateDefinition(
      id = "geneva_humanitarian",
      name = "Geneva Humanitarian",
      category = TemplateCategory.GLOBAL,
      atsScore = 95,
      isAtsSafe = true,
      supportsPhoto = false,
      layout = LayoutStructure.SINGLE_COLUMN,
      typography = TypographyStyle.SERIF_EDITORIAL,
      primaryAccentHex = "#72232B",
      secondaryColorHex = "#52171E",
      dividerStyle = DividerStyle.HAIRLINE,
      description = "Tailored for Red Cross, WHO, and international humanitarian agency postings.",
      tags = listOf("Geneva", "Humanitarian", "Field Work")
    )
  )

  fun getById(id: String): TemplateDefinition {
    return templates.find { it.id == id } ?: templates.first()
  }

  fun filter(
    category: TemplateCategory = TemplateCategory.ALL,
    atsOnly: Boolean = false,
    photoOnly: Boolean = false,
    query: String = ""
  ): List<TemplateDefinition> {
    return templates.filter { t ->
      (category == TemplateCategory.ALL || t.category == category) &&
      (!atsOnly || t.isAtsSafe) &&
      (!photoOnly || t.supportsPhoto) &&
      (query.isEmpty() || t.name.contains(query, ignoreCase = true) || t.description.contains(query, ignoreCase = true) || t.tags.any { it.contains(query, ignoreCase = true) })
    }
  }
}
